defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/ruby:2.3-node-browsers

version: 2
jobs:
  clone_repo:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

  install_nm:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm install
      - run: npm install
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules

  build_npm:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm run build
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

  install_gems:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle install --deployment --path vendor/bundle
      - persist_to_workspace:
          root: ~/app
          paths:
            - vendor/bundle

  build_jekyll:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle config --local path vendor/bundle
      - run: bundle exec jekyll build
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

  deploy_staging:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: STAGING=true bundle exec s3_website push --site _site/

  deploy_production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: cd deployment; bundle install; bundle exec cap production deploy

workflows:
  version: 2
  build_and_push:
    jobs:
      - clone_repo

      - install_nm:
          requires:
            - clone_repo

      - install_gems:
          requires:
            - clone_repo

      - build_npm:
          requires:
            - install_nm

      - build_jekyll:
          requires:
            - build_npm
            - install_gems

      - deploy_staging:
          requires:
            - build_jekyll
          filters:
            branches:
              only: master

      # - deploy_production:
      #     requires:
      #       - build_jekyll
      #     filters:
      #       branches:
      #         only: production
