defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/ruby:2.3-node

clone_repo: &clone_repo
  <<: *defaults
  steps:
    - checkout
    - persist_to_workspace:
        root: ~/app
        paths:
          - .

version: 2
jobs:
  staging:
    <<: *clone_repo

  production:
    <<: *clone_repo

  install_nm:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm install
      - run: npm install
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules

  build_npm:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm run build
      - persist_to_workspace:
          root: ~/app
          paths:
            - build

  install_gems:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle install --deployment --path vendor/bundle
      - persist_to_workspace:
          root: ~/app
          paths:
            - vendor/bundle

  install_deployment_gems:
    <<: *defaults
    working_directory: ~/app/deployment
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle install --deployment --path vendor/bundle
      - persist_to_workspace:
          root: ~/app
          paths:
            - deployment/vendor/bundle

  build_jekyll:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle config --local path vendor/bundle
      - run: bundle exec jekyll build
      - persist_to_workspace:
          root: ~/app
          paths:
            - _site

  deploy_staging:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle config --local path vendor/bundle
      - run: STAGING=true bundle exec s3_website push --site _site/

  deploy_production:
    <<: *defaults
    working_directory: ~/app/deployment
    steps:
      - attach_workspace:
          at: ~/app
      - run: bundle config --local path vendor/bundle
      - run: bundle exec cap production deploy

workflows:
  version: 2
  build_and_push:
    jobs:
      - staging:
          filters:
            branches:
              only: master

      - production:
          filters:
            branches:
              only: production

      - install_nm:
          requires:
            - staging

      - install_gems:
          requires:
            - staging

      - build_npm:
          requires:
            - install_nm

      - build_jekyll:
          requires:
            - build_npm
            - install_gems

      - deploy_staging:
          requires:
            - build_jekyll

      - install_deployment_gems:
          requires:
            - production

      - deploy_production:
          requires:
            - install_deployment_gems

